# Generated by Django 5.1.4 on 2025-01-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
