# Generated by Django 5.1.4 on 2025-01-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
