# Generated by Django 5.1.4 on 2025-01-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
